modLoader = "javafml"
loaderVersion = "[47,)"
license = "CC-BY-NC-SA-4.0"

[[mods]]
modId = "linguaperipherals"
version = "2.0.2"
displayName = "Lingua Peripherals"
displayURL = "https://github.com/DrAsm/linguaperipherals"
credits = "Dr_Asm"
authors = "Dr_Asm"
logoFile = "linguaperipherals.png"
description = "A CC: Tweaked addon that adds language-related peripherals."

[[dependencies.linguaperipherals]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.linguaperipherals]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.linguaperipherals]]
    modId = "computercraft"
    mandatory = true
    versionRange = "[1.109,)"
    ordering = "NONE"
    side = "BOTH"
